### ISSUE TITLE
CI - Formalize releases

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio-connectors#135] opened 2022-01-31 20:11 UTC
Since we are trying to semantic version the connectors, we should formalize the releases by uploading artifacts.

Follow Fluvio's model.

Artifacts:
- Binary
- Docker image tarball (? not sure if this is too large)

**Comment by nacardin** [comment] 2022-02-07 19:50
Duplicate of https://github.com/infinyon/fluvio-connectors/issues/77

**Closed by nacardin** 2022-02-07 19:50 UTC
